#!/usr/bin/env bash
file_path=$1
server_ip=$2
name=$3
ssh_key=$4
if [ "$#" -ne 4 ]; then
	echo "usage: ./0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi
# lets transfeer fileusing scp
scp -i "ssh_key" -o StrictHostKeyChecking=no "file_path" "name@server_ip:~/"

# lets check if successful
if [ "#?" -ne o]; then
	echo "File transfer failed"
	exit 1
else
	echo "File transerred successfully"
	exit 0
fi
