#!/usr/bin/env bash
# install nginx

# updating package
apt-get -y update
apt-get -y install nginx

# Allow http traffic wit utw firewall
ufw allow 'Nginx HTTP'

#configuring to server
echo "Hello World!" > /var/www/html/index.nginx-debian.html

service nginx start

# confirm Nginx is running by using curl
