#!/usr/bin/env bash
#Bash script that displays the time for 12 hours and 59 minutes:
#display hours from 0 to 12
#display minutes from 1 to 59
hours=0
min=0
while [ $hours -lt 12 ]; do
	echo "Hour: $hours"
	while [ $min -lt 60 ]; do
		echo "$min"
		((min++))
	done
	min=0
	((hours++))
done
