#!/usr/bin/env bash
#  Bash script that gives you information about the school file.
school="school.txt"

if [ -e $school ]; then
	echo "school file exists"

	if [ -f $school ]; then
               echo "school is a regular file"
	fi
	if [ -s $school ]; then
		echo "school file is empty"
	else
		echo "school file is not empty"
	fi
else
	echo "school file does not exist"
        exit 1
fi
